'''
*******************************************************************
* File Name         : cam_cal.py

* Description       : develop camera parameters to counteract distortion
*        
* Supplementary files: take_photo.py generates photos of checkerboard that get stored in images folder    
* References:   https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html
* https://github.com/niconielsen32/CameraCalibration/blob/main/calibration.py
* Revision History  :
* Date		Author 			Comments
* ------------------------------------------------------------------
* 
* 02/12/2025    Kobe Prior and Blane Miller Created File
******************************************************************
Hardware Setup: N/A
Example Excecution: navigate to the directory that holds this file
'''

# import necessary libraries
import numpy as np
import cv2 as cv
import glob


chessboardSize = (9,6)

# get images generated by take_photo.py file
images = glob.glob('images/*.png')